### PR TITLE
Add api endpoint for connecting disconnecting node.

### PR DESCRIPTION
**Pull request by a-urth**
#185

### CODE REVIEW

**Comment by a-urth** [comment]
Added `restart` cli command and corresponding endpoint with `hard` flag which wipes db if its present.

**Comment by rkeene** [comment]
I think this needs some sort of authentication system built first (or as part of this changeset, even) so that anonymous users on the Internet don't wipe our testnet (or even disconnect/connect random nodes to our cluster).

**Comment by a-urth** [comment]
@rkeene i think api is designed to be used from lens only, if node won't be exposed to external world (by http) this should not be a problem

**Comment by rkeene** [comment]
Currently, on the testnet we do expose the HTTP API to the world and nothing in this PR seems to restrict it as far as I can tell...

**Comment by a-urth** [comment]
@rkeene i don't think that its possible to connect to testnet outside of lens or clicker as of now
@iwasaki-kenta ? and your opinion an auth for api in general

**Comment by rkeene** [comment]
https://testnet.perlin.net/   leads directly to the HTTP API for the testnet.

For example:

```
$ curl -sSL https://testnet.perlin.net/ledger | jq --tab .
{
        "public_key": "0f569c84d434fb0ca682c733176f7c0c2d853fce04d95ae131d2f9b4124d93d8",
        "address": "10.0.13.124:3000",
        "num_accounts": 1286,
        "round": {
                "merkle_root": "87cfefa37b967555890f0366d29e93bc",
                "start_id": "41586bd3a7fd5a5881393304dedbea16f6d9b2d7c83e24fcd9b3d8bda63e5dd9",
                "end_id": "2cf5ed86b3fcb1e02a6ad23d222c55052e689222b291a27d90e35573a6964c01",
                "applied": 8,
                "depth": 8,
                "difficulty": 8
        },
        "peers": [
                {
                        "address": "10.0.13.121:3002",
                        "public_key": "ba41cbb19074d27727607992e123345dd82f1fc115233b5ae43a07c00ddda3df"
                },
                {
                        "address": "10.0.13.123:3001",
                        "public_key": "487cbbbf68fc15d67a1a074951172b4cfd043489e93d7ae71c8e4aa0be1593b0"
                }
        ]
}
```

**Comment by iwasaki-kenta** [comment]
@rkeene Can you leave feedback on what the ideal authentication system would be given the Docker Swarm setup?

**Comment by rkeene** [comment]
For the Docker Swarm setup it would be ideal if there were a simple shared secret that were used.

The simplest implementation I can think of would be a CLI flag `--api.secret` (and accompanying environment variable) containing to specify that value, or if not specified either those APIs are disabled or a random 256-bit hex-encoded value is used (and displayed to the user, similar to the node's private key -- it could even *BE* the node's private key).

To use it, each request would need to include it as a parameter:

```json
{
        "api_secret": "<sharedSecret>",
        "host": "<host>",
        "port": <port>
}
```

**Pull request merged**
